#!/bin/bash

# Check that we have markdown installed
METADATA_LINE_COUNT=4
WORKING_DIR=$(pwd)
HAS_MARKDOWN=$(which markdown | wc -l)
if [ $HAS_MARKDOWN -eq 0 ]; then
    echo "Please install markdown"
    exit -1
fi

# Create the output path
OUTPUT_PATH="out"
rm -r $OUTPUT_PATH
mkdir $OUTPUT_PATH

# We'll also use Markdown for the index
touch index.md
echo -e "<ul>" >> index.md
touch temp

# Time to build the site!

# Grab all the markdown files and make them into HTML
for markdownFile in $(find . -name '*.md' | sort); do
    FILENAME=$(basename $markdownFile)
    OUTPUTNAME=${FILENAME%.*}.html
    FULLPATH=$(dirname $markdownFile)
    RELATIVE_DIR=${FULLPATH/$WORKING_DIR/$OUTPUTPATH}
    RELATIVE_DIR=${RELATIVE_DIR/./}
    OUTPATH="$OUTPUT_PATH$RELATIVE_DIR/$OUTPUTNAME"
    TITLE=${FILENAME%.*}

    METADATA=$(cat $markdownFile | head -n $METADATA_LINE_COUNT)
    HAS_METADATA=$(echo "$METADATA" | head -n 1)
    if [ $HAS_METADATA = "<!--" ]; then
        TITLE=$(echo "$METADATA" | head -n 2 | tail -n 1)
        DATE=$(echo "$METADATA" | tail -n 2 | head -n 1)
        # Date conversions in macOS: https://stackoverflow.com/a/43927574
        # This would add the date to the index, but we need to convert it to
        # *some* timezone from UTC. It's unclear what this should be.
        # echo -e "$DATE " >> index.md
        echo -e "<li>\n" >> index.md
        echo -e "[$TITLE]($RELATIVE_DIR/$OUTPUTNAME)\n" >> index.md
        cat $markdownFile >> index.md
        echo -e "</li>\n" >> index.md
    fi

    # Make directories until the outpath
    mkdir -p $OUTPATH
    # ...but delete the actual directory that was made for this filename
    rm -r $OUTPATH
    # Touch the file we'll output to
    touch $OUTPATH
    # Do the actual markdown generation
    cat $markdownFile | markdown > $OUTPATH

    # Do some post-processing
    # Insert before.html at the beginning
    cat before.html $OUTPATH > temp

    # Insert after.html at the end
    cat temp after.html > $OUTPATH

    sed -i '' -e "s/TITLE_HERE/$TITLE/g" $OUTPATH
done

rm index.md
rm temp

# Copy over css
cp style.css out/

# Copy over the media directory
cp -r media out/

# Finally, remove readme from output (we don't want included)
rm $OUTPUT_PATH/readme*
