#!/usr/bin/env python3

import json
import sys

tiddler_path = sys.argv[1]
out_tiddler_data = []

with open(tiddler_path, 'r') as tiddler_file:
    tiddler_data = json.load(tiddler_file)
    for tiddler in tiddler_data:
        for field in tiddler.keys():
            if field.startswith("public_"):
                newFieldName = field.replace("public_", "", 1)
                tiddler[newFieldName] = tiddler.get(field, "")
        out_tiddler_data.append(tiddler)

with open(tiddler_path, 'w') as tiddler_file:
    json.dump(out_tiddler_data, tiddler_file)

