---
- name: setup freshrss
  hosts: site
  tasks:
    - name: Make rss root
      file:
        path: /home/phajas/services/rss
        state: directory
    - name: Make rss config
      file:
        path: /home/phajas/services/rss/config
        state: directory
    - name: Create freshrss Container
      containers.podman.podman_container:
        name: freshrss
        image: lscr.io/linuxserver/freshrss:latest
        expose: 80
        env:
          VIRTUAL_PORT: 80
          VIRTUAL_HOST: 'rss.peterhajas.com'
          LETSENCRYPT_HOST: 'rss.peterhajas.com'
          HTTPS_METHOD: redirect
        volumes:
          - /home/phajas/services/rss/config:/config:z
        network:
        - podman
