---
- name: setup nginx_server
  hosts: site
  tasks:
    - name: Make HTML root
      file:
        path: /home/phajas/html
        state: directory
    - name: Create nginx_server Container
      containers.podman.podman_container:
        name: nginx_server
        image: docker.io/nginx:1.27.0
        expose: 80
        env:
          VIRTUAL_PORT: 80
          VIRTUAL_HOST: peterhajas.com,demo.peterhajas.com
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/phajas/html:/usr/share/nginx/html:z
        network:
        - podman
