---
- name: Set up home directory
  hosts: site
  tasks:
    - name: Make roots
      file:
        path: "/home/phajas/{{ item }}"
        state: directory
      loop:
        - phajas-wiki.git
        - password-store
    - name: Initialize repos
      ansible.builtin.shell: "git init {{ item }}"
      loop:
        - password-store
    - name: Initialize wiki
      ansible.builtin.shell: "git init --bare phajas-wiki.git"
